### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by scp145** [Pylo/MCreatorGenerator-Forge-1.12.2#11]
i like if you can make the 1.12.2.14.23.5.2854 forge
because im making a scp map in 1.12.2 and i think that i can add new blocks but minecraft says that the scp mod needs 1.12.2.14.23.5.2776 so i want the final forge version if you can, if you don't can do the forge doesn't matter.
(sorry bad english xd)

**Comment by KlemenDEV** [comment]
We are targeting the recommended release due to the amount of testing needed for a more recent version. Feel free to change version in  number in https://github.com/Pylo/MCreatorGenerator-Forge-1.12.2/blob/2020.5/forge-1.12.2/generator.yaml.

But it could introduce problems in code that would require manual fixing and attention.
