### ISSUE TITLE
Is there a plan to update 2021.2?

### ISSUE THREAD

**Issue by 3284987829** [Pylo/MCreatorGenerator-Forge-1.12.2#53]
I want to be able to use it on 2021.2.Forgive me, I can't write code. I really need him to add some new features.

**Comment by Toma400** [comment]
As far as I know, there is no plan to port it to 2021.2, but it should be compatibile with it, just with some limitations (no possibility to run environmental test)
But even environmental test can be possible with additional effort. Quoting Klemen on that "1.12.2 could even run client on 2021.2 if combined with gradle toolchains api" (sorry @KlemenDEV for citation :P)

Also! You can store both 2021.1 and 2021.2 on your PC, just remember to install them in different directories. I - who personally prefer 2020.2 over plugin - use several versions (2020.2, 2020.5, 2021.1) and they all work totally fine. Since 2021.2 doesn't add anything new for 1.12 plugin, it makes sense to stay on older versions.
